version: '3'
services:
  apisix:
    profiles: ["test"]
    build:
      context: .
    volumes:
      - ./t/demo:/usr/local/apisix-plugin-test/t/demo
      - ./apisix/plugins/demo.lua:/usr/local/apisix-plugin-test/apisix/plugins/demo.lua
    depends_on:
      - etcd
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.4.15
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local
