name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-20.04

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Check out APISIX plugins
        uses: actions/checkout@v2.4.0
        with:
          path: apisix-plugin

      - name: Check out APISIX repo
        run: |
          sudo ./apisix-plugin/ci/utils/linux-common-runnner.sh get_apisix_code

      - name: Install custom module
        run: |
          sudo ./apisix-plugin/ci/utils/linux-common-runnner.sh install_module

      - name: Launch APISIX env
        run: |
          sudo make ci-env-up project_compose_ci=ci/pod/docker-compose.common.yml
        working-directory: apisix
