name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-20.04

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Check out APISIX plugins
        uses: actions/checkout@v2.4.0
        with:
          path: apisix-plugin

      - name: Check out APISIX repo
        run: |
          sudo ./ci/utils/linux-common-runnner.sh get_apisix_code
        working-directory: apisix-plugin
